### ISSUE TITLE
Octal literal in strict mode

### ISSUE THREAD

**Issue by ryanflorence** [0x00A/prompt-sync#12]
![d10fb780-daed-11e5-8e45-ec7c54618b10](https://cloud.githubusercontent.com/assets/100200/13291298/12fb3a10-dacc-11e5-85ee-fc8f9c2cc8dc.png)

as seen in https://github.com/ryanflorence/react-project/issues/4

**Comment by 0x00A** [comment]
fixed in `+ prompt-sync@3.0.2`
