### ISSUE TITLE
cant paste properly

### ISSUE THREAD

**Issue by ryanramage** [0x00A/prompt-sync#19]
on osx, I am trying to paste a password. Only the last character of seems to get set. I have tried in both a hide and regular prompt.

**Comment by 0x00A** [comment]
hmm, im not able to reproduce this -- so you are saying that only the last character gets copied to the clipboard?

**Comment by ryanramage** [comment]
yes. I switched to a different module, so not sure why it was happening, but that was the behaviour I saw. I will close for now.
