### ISSUE TITLE
[request] Set term or set terminating function

### ISSUE THREAD

**Issue by kyleshrader** [0x00A/prompt-sync#30]
It would be nice if we could override the termination key, or pass in our own boolean function to determine the case for termination.

**Comment by yegodz** [comment]
can you describe a use case? what type of character or Boolean function are you thinking of for termination

**Comment by kyleshrader** [comment]
I was hoping to alter this for a personal tool that would accept multi-line input.

**Comment by yegodz** [comment]
yeah .. good point. Only problem is the multiline messes up the line edit mode.. 
Really hard to enter the newline character and then still handle backspace etc. 
Easy way to handle would be to simply accept one line at a time until you see a end sequence and just concat the lines received together.
