### ISSUE TITLE
@davidmarkclements - can you push the latest change to npm?

### ISSUE THREAD

**Issue by yegodz** [0x00A/prompt-sync#32]
Hi David
I've merged a fix - can you push that to npm?
Alternatively, please add me as a collaborator for prompt-sync on npm so I can update and maintain
Thanks

**Comment by davidmarkclements** [comment]
hey @yegodz this is published – 

@0x00A are we cool to add @yegodz as npm collab?

**Comment by yegodz** [comment]
thanks @davidmarkclements
