### ISSUE TITLE
Every time I type a letter, the line repeats itself

### ISSUE THREAD

**Issue by ThatOneCalculator** [0x00A/prompt-sync#44]
```js
const prompt = require('prompt-sync')();
const go = prompt('Every time I type a letter, the prompt is repeated.\n');
```
![Screenshot](https://media.discordapp.net/attachments/691827873941553172/799428183224746034/unknown.png)

**Comment by jsjain** [comment]
This is happening for me as well, but only when the question ends with `\n` or `\t`

**Comment by ThatOneCalculator** [comment]
> This is happening for me as well, but only when the question ends with `\n` or `\t`

Yeah. I'm just using sync-prompt now lol.

**Comment by harsh-sri** [comment]
don't use `\n`.

@ThatOneCalculator @jsjain

**Comment by jsjain** [comment]
I need to show a new line after displaying the question.

**Comment by harsh-sri** [comment]
> I need to show a new line after displaying the question.

for next command?

**Comment by jsjain** [comment]
no for users to enter answer to the question

**Comment by paiva-thiago** [comment]
It happens here in windows when I use the git prompt or the powershell.

**Comment by Tusharnalawade11** [comment]
> no for users to enter answer to the question

Use another console.log  for that

**Comment by joshuabremerdexcom** [comment]
If it's not clear to people, this is what I did:

```
const prompt = require('prompt-sync')();


console.info('Are you sure you want to continue? (y/N)');
if (prompt('> ').toLowerCase() !== 'y') {
  logger.info('Exiting!');
  process.exit(1);
}
```

**Comment by ThePhilgrim** [comment]
I have the same issue when the prompt question is too long (even without an explicit \n.

`let foo = prompt("Great, the field will be 10x10. How many percent do you want to be covered in mines? (Enter a number between 1 - 60): ")`

creates the same issue.

**Comment by ThatOneCalculator** [comment]
Point being don't use this package. Please stop pinging me with this it's been literally a year geez
